### PR TITLE
Update app.xql

### PR DESCRIPTION
**Pull request by jensopetersen**
Constructing Lucene queries with XML syntax, based on code by Ron Van den Branden.

### CODE REVIEW

**Comment by joewiz** [comment]
These are great, Jens.  Looking at these commits as a whole in https://github.com/wolfgangmm/ShakespeareDemo/pulls, it strikes me that the title for each commit - drawn from the default, I'm sure - isn't very descriptive.  I'd suggest that we try put the heart of the commit message in the title, leaving any spill over for the fuller description.  What do you think?

**Comment by jensopetersen** [comment]
Thanks, Joe. Yes, the situation with the ShakespeareDemo is a little complicated for me (or for my git-skills), since I also build the mystery standoff editor on top of this, and have to (?) patch these by editing in GitHub. I will try to be more descriptive in the commit message titles (which are indeed default). - I will be moving some stuff I added to an app of Wolfgang's https://github.com/jensopetersen/Deutsche-Gesetze to the ShakespeareDemo. Actually, right now I was also thinking about changing the structure of the transform to the one you used in your Punch demo. What do you think?

**Comment by joewiz** [comment]
Cool app!  I like the advanced search features and how you've exposed them; I'd like to do something similar at http://history.state.gov/search.  As to the structure of the transform used in Punch, do you mean the transform in your app.xql's `app:process()` function?  The change would be to break each `case return` into its own function?  That is definitely useful when the handling rules get complex; I think you're on the edge of this now.  Or do you mean a different transform?

**Comment by jensopetersen** [comment]
I mean what you are hinting. You think it is overkill? Well, I might do it anyway, since I am using this as a steeping-stone to a larger TEI app (for Sanskrit texts).

**Comment by joewiz** [comment]
In that case, I'd suggest doing it.  I find it helps with readability.  With one line per `case`, it makes looking up the relevant function quite nice.  Sanskrit, eh?  Does Lucene have an analyzer for Sanskrit? :)

**Comment by wolfgangmm** [comment]
Hi Jens,

I wonder how you managed to create so many pull requests? Normally if you send one pull request, all following commits should be added to the existing request automatically. 

Right now I'm getting some merge conflicts and will have to merge manually. 

Wolfgang

**Comment by jensopetersen** [comment]
Hi Wolfgang,

Sorry about that, I will try to do it in another way. I get so many because I edit inside GitHub. My fork of Shakespeare is used for the standoff editor. 

Have a nice holiday,

Jens

Sent from my HTC

----- Reply message -----

**Comment by jensopetersen** [comment]
Can't I just close (withdraw, cancel) the earlier pull requests that relate to the same file and keep the newest one, updating the comments? Will that solve the merge problem?

----- Reply message -----

**Comment by wolfgangmm** [comment]
Merged manually.

**Comment by wolfgangmm** [comment]
Hi Jens,

I merged all pull requests. Sometimes there were just whitespace changes, so I'm not sure all your desired changes are in now. Anyway, you should not edit inside GitHub. If you have other changes in your fork, you can either stash them (put them into a temporary buffer) or work with multiple branches.

**Comment by jensopetersen** [comment]
Thanks, I will work on my git skills!

On 29 May 2014 at 10:18:37, Wolfgang Meier (notifications@github.com) wrote:

Hi Jens,

I merged all pull requests. Sometimes there were just whitespace changes, so I'm not sure all your desired changes are in now. Anyway, you should not edit inside GitHub. If you have other changes in your fork, you can either stash them (put them into a temporary buffer) or work with multiple branches.

**Pull request closed without merging**
